### ISSUE TITLE
Soundpack doesn't work

### ISSUE THREAD

**Issue by Aphyxia** [asiekierka/littleMaidMobX#2]
Tested my setup also with 0.0.8pre3 and 0.0.9 and it worked.
With this version of littleMaidMob maids do NOT have ghast sounds but sounds from the soundpack don't play either. So it seems like the mod recognises that there are custom sounds allocated but can't find them?

This is my setup:
http://gyazo.com/c1fe78bd9044677c5c902a9cd6488739

**Comment by EndridTelek** [comment]
Yeah. When i switched to LMMAX to fix the skin problem, i did not hear the maids anymore.

**Comment by asiekierka** [comment]
Fixed!

**Comment by Aphyxia** [comment]
Compiled it (had to remove the random ` in MMM_ProxyClient) but sounds do not work. Must they be situated somewhere else or?
